package:
    name:           yii2-pluginmanager
    namespace:      hiqdev\pluginmanager
    label:          PluginManager
    title:          Plugin Manager for Yii2
    type:           yii2-extension
    keywords:       plugin, manager, extension, yii2
    year:           2015

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
