package:
    type:           yii2-extension
    name:           yii2-pluginmanager
    namespace:      hiqdev\pluginmanager
    headline:       Yii2 Plugin Manager
    title:          Plugin Manager for Yii2
    keywords:       plugin, manager, extension, yii2
    year:           2015
    description:    |
        Provides plugin system for Yii2.
        Automatic loading of plugins configurations with caching.

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-hiqdev: "*"
